version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    labels:
      - dependencies

  - package-ecosystem: cargo
    directory: "/rust"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    labels:
      - dependencies

  - package-ecosystem: npm
    directory: "/typescript"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    labels:
      - dependencies

  - package-ecosystem: mix
    directory: "/elixir"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    labels:
      - dependencies

  - package-ecosystem: uv
    directory: "/python"
    schedule:
      interval: weekly
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
    labels:
      - dependencies
