name: PR meta

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-meta:
    uses: ostara-labs/devtools/.github/workflows/pr-meta.yml@a33b83f40da51cc62564d739606b558380aa6472 # v1.7.0
