name: PR meta

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-meta:
    uses: ostara-labs/devtools/.github/workflows/pr-meta.yml@4c5f2593b127455822a7f7d150d1832d589c50a5 # v1.12.1
