name: PR meta

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-meta:
    uses: ostara-labs/devtools/.github/workflows/pr-meta.yml@e5ae119a756e85177f8d86f68627301357df60c7 # v1.10.0
